Add ActiveHelp to the cobra-cli
The below messages have been added.

$ cobra-cli init <TAB>
Optionally specify the path of the go module to initialize
--
CONDUCT.md       LICENSE.txt      Makefile         bin/             go.mod           main.go
CONTRIBUTING.md  MAINTAINERS      README.md        cmd/             go.sum           tpl/

$ cobra-cli init newprogram <TAB>
This command does not take any more arguments (but may accept flags)

$ cobra-cli init newprogram extra <TAB>
ERROR: Too many arguments specified

$ cobra-cli add <TAB>
Please specify the name for the new command

$ cobra-cli add command <TAB>
This command does not take any more arguments (but may accept flags)

$ cobra-cli add command command2 <TAB>
ERROR: Too many arguments specified

Signed-off-by: Marc Khouzam <marc.khouzam@gmail.com>